### ISSUE TITLE
Validate vendor backends for the Flutter app

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#231] opened 2022-01-25 09:45 UTC
We need to test the app to see if it correctly works with vendor backends.
We have few known issues:
* App doesn't have a special handling for the Samsung backend.
Test APK where issues with Samsung backend should be fixed is located in a comment here:
https://github.com/mlcommons/mobile_app_open/issues/177#issuecomment-1011790919
* App crashes on Qualcomm phones.
The discussion can be found in this closed issue:
https://github.com/mlcommons/mobile_app_open/issues/159

We need to test the app on phones that use different vendor backends to check if any backends other than the Qualcomm have any issues.

APK for Samsung backend can be downloaded from the link above.
APK for all other backends can be found here:
https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0.0-flutter-android-alpha-4

**Comment by d-uzlov** [comment] 2022-01-25 09:50
@relja128 @freedomtan @Mostelk @mohitmundhragithub @jwookiehong 
Could you please test the app on devices available to you if/when you have the time?

**Comment by freedomtan** [comment] 2022-01-27 03:41
@d-uzlov 

FYR, it seems to be in on MTK phones. But the the offline issue is weird. I didn't look into it.

Oppo Reno 6 Pro (Color OS V11.3, MediaTek Dimensity 1200)
- Looks fine

Xiaomi Mi11 (MIUI 13.0 Stable 13.0.5.0 (SKBCNXM), Qualcomm 888)
- Crashed when running more than 1 test (single test looks to be fine)
- Crashed when running Image classification (offline)

Pixel 6
- Crashed when running Image classification (offline)

add @ptt2panda for Pixel 6

**Comment by mohitmundhragithub** [comment] 2022-01-27 14:52
We also tried in our internal devices, and still see the crassh, just like the one reported on Xiaomi Mi11 above. 
@AasheeshT  is trying out few things to debug the reason for the crash.

**Comment by freedomtan** [comment] 2022-02-15 06:15
We should revisit this one as soon as possible after the v2.0 submission.

**Comment by freedomtan** [comment] 2022-03-01 06:10
@anhappdev please try to build a new flutter app based on 2.0 submission (so that we have new SNPE runtime).

**Comment by anhappdev** [comment] 2022-03-01 10:26
I got an error building the Flutter app with `snpe-1.59.1.3230`. Branch `submission-v2.0` (commit `2ed3ddd2ce83e883a2a493f063202625bcc44dda`) was used.

```
ERROR: /mnt/project/mobile_back_qti/BUILD:28:11: SolibSymlink _solib_arm64-v8a/_U_S_Smobile_Uback_Uqti_Csnpe___Umobile_Uback_Uqti_Ssnpe-1.59.1.3230_Slib_Saarch64-android-clang6.0/libSNPE.so failed: missing input file '//mobile_back_qti:snpe-1.59.1.3230/lib/aarch64-android-clang6.0/libSNPE.so'
ERROR: /mnt/project/mobile_back_qti/BUILD:28:11 SolibSymlink _solib_arm64-v8a/_U_S_Smobile_Uback_Uqti_Csnpe___Umobile_Uback_Uqti_Ssnpe-1.59.1.3230_Slib_Saarch64-android-clang6.0/libSNPE.so failed: 1 input file(s) do not exist
```

**Comment by mohitmundhragithub** [comment] 2022-03-02 06:41
@anhappdev , you need to apply the patch from https://github.com/mlcommons/submissions_mobile_2.0/tree/main/closed/Qualcomm_Innovation_Center/code over the submission-v2.0 branch to be able to use snpe-1.59.1.3230 SDK.

**Comment by dylanzika-google** [comment] 2022-03-02 23:23
@ptt2panda What was our status on testing on the flutter app last we checked? Google was running into app errors or crashes correct?

Do you have any more information on the fails / errors?

**Comment by freedomtan** [comment] 2022-03-03 02:10
@anhappdev did you test it on any Qualcomm devices? I get stuck in the loading models screen on Xiaomi Mi 11.
![mi11_alpha5](https://user-images.githubusercontent.com/3395998/156482758-4631c67a-e8f4-4902-8503-e7a34f0d531a.png)

**Comment by ptt2panda** [comment] 2022-03-03 03:24
@anhappdev 
Flutter app can finish on Pixel 6.
However, from the number I saw, it seems that the configuration in Pixel backend was not used. Could you help us verify this?

**Comment by anhappdev** [comment] 2022-03-03 03:40
> @anhappdev did you test it on any Qualcomm devices? I get stuck in the loading models screen on Xiaomi Mi 11.
it seems flutter doesn't work with /sdcard/mlperf_models

@freedomtan Since the Flutter app needs to support multiple platform, there is some restriction how to load resources from disk. You need to copy the models to certain location and change the path in task file. Please see https://github.com/mlcommons/mobile_app_open/blob/master/flutter/documentation/custom-tasks.md#using-external-resources-on-an-android

**Comment by anhappdev** [comment] 2022-03-03 03:42
> @anhappdev Flutter app can finish on Pixel 6. However, from the number I saw, it seems that the configuration in Pixel backend was not used. Could you help us verify this?

@ptt2panda Which APK did you use? If you used the one from [this comment](https://github.com/mlcommons/mobile_app_open/issues/231#issuecomment-1056769024) then it doesn't include Pixel backend.

**Comment by ptt2panda** [comment] 2022-03-03 03:44
I see, I'm using the wrong one then. Which one should I use?

**Comment by anhappdev** [comment] 2022-03-03 03:45
> I see, I'm using the wrong one then. Which one should I use?

This: https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0.0-flutter-android-alpha-4

**Comment by ptt2panda** [comment] 2022-03-03 05:07
@dylanzika-google  I'm seeing LU & OD scores are lower than expected. And IC_offline is still crashing.

**Comment by anhappdev** [comment] 2022-03-04 03:30
@ptt2panda Do you think TensorFlow 2.8 would resolve the issue you encountered? The Flutter app is built using TF 2.6, but I can build a version with TF 2.8 for testing.

**Comment by ptt2panda** [comment] 2022-03-07 01:29
From the log, the issue doesn't look to be related to TensorFlow version. 
Could you try to build with the latest pixel_v2.0 branch? Let me check if I can find something there...

**Comment by anhappdev** [comment] 2022-03-07 10:49
> From the log, the issue doesn't look to be related to TensorFlow version.
Could you try to build with the latest pixel_v2.0 branch? Let me check if I can find something there...

@ptt2panda Please try this build
[2022-03-07_mlperfbench_v3.0-alpha5-g.apk](https://drive.google.com/file/d/1ocMxuwzT64UFBN1m7onhWR-7B88QC1Uz/view?usp=sharing)
Note: Build with branch `pixel_v2.0`, commit `8ac47943d435230af712a2974a6bd2aadf364189`, Pixel backend only.

**Comment by freedomtan** [comment] 2022-03-07 13:56
FYR. With [2022-03-07_mlperfbench_v3.0-alpha5-g.apk](https://drive.google.com/file/d/1ocMxuwzT64UFBN1m7onhWR-7B88QC1Uz/view?usp=sharing), I got reasonable scores on Pixel 6.

<img src="https://user-images.githubusercontent.com/3395998/157047299-2fed3569-c83b-430e-9d1a-d708fbe7fbfc.png" width="200"/>

**Comment by anhappdev** [comment] 2022-03-07 15:13
> FYR. With [2022-03-07_mlperfbench_v3.0-alpha5-g.apk](https://drive.google.com/file/d/1ocMxuwzT64UFBN1m7onhWR-7B88QC1Uz/view?usp=sharing), I got reasonable scores on Pixel 6.

And no crash when running Image classification (offline)?
Then we just wait to merge the branch `pixel_v2.0` into master.

**Comment by freedomtan** [comment] 2022-03-07 23:10
> > FYR. With [2022-03-07_mlperfbench_v3.0-alpha5-g.apk](https://drive.google.com/file/d/1ocMxuwzT64UFBN1m7onhWR-7B88QC1Uz/view?usp=sharing), I got reasonable scores on Pixel 6.
> 
> And no crash when running Image classification (offline)? Then we just wait to merge the branch `pixel_v2.0` into master.

Nope, no crash when running Image Classification (offline). However,
1. the Pixel 6 runs [Android 13 Developer Preview 1](https://android-developers.googleblog.com/2022/02/first-preview-android-13.html)
2. it seems there are more than one TFLite instance for non-offline ones. @ptt2panda is this expected behavior?

**Comment by fatihcakirs** [comment] 2022-03-08 01:56
@anhappdev Tried two apk’s shared in this folder on Samsung S21+ with the Exynos.

1. https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0.0-flutter-android-alpha-4 (mlperfbench-v3.0-alpha4-qsmgt.apk). Crashes shortly after the completion of a single/first benchmark
2. https://github.com/mlcommons/mobile_app_open/issues/177#issuecomment-1011790919 (mlperfbench-v3.x-samsung-test-2.apk). IC offline crashes. Other benchmarks work OK.

**Comment by freedomtan** [comment] 2022-03-08 02:40
> > @anhappdev did you test it on any Qualcomm devices? I get stuck in the loading models screen on Xiaomi Mi 11.
> > it seems flutter doesn't work with /sdcard/mlperf_models
> 
> @freedomtan Since the Flutter app needs to support multiple platform, there is some restriction how to load resources from disk. You need to copy the models to certain location and change the path in task file. Please see https://github.com/mlcommons/mobile_app_open/blob/master/flutter/documentation/custom-tasks.md#using-external-resources-on-an-android

there is no field to specify model path in [task proto](https://github.com/mlcommons/mobile_app_open/blob/master/android/cpp/proto/mlperf_task.proto). Model path is specified in backend setting's [BenchmarkSettings](https://github.com/mlcommons/mobile_app_open/blob/master/android/cpp/proto/backend_setting.proto#L41)

**Comment by freedomtan** [comment] 2022-03-08 05:16
> > > FYR. With [2022-03-07_mlperfbench_v3.0-alpha5-g.apk](https://drive.google.com/file/d/1ocMxuwzT64UFBN1m7onhWR-7B88QC1Uz/view?usp=sharing), I got reasonable scores on Pixel 6.
> > 
> > 
> > And no crash when running Image classification (offline)? Then we just wait to merge the branch `pixel_v2.0` into master.
> 
> Nope, no crash when running Image Classification (offline). However,
> 
> 1. the Pixel 6 runs [Android 13 Developer Preview 1](https://android-developers.googleblog.com/2022/02/first-preview-android-13.html)
> 2. it seems there are more than one TFLite instance for non-offline ones. @ptt2panda is this expected behavior?

update, I flashed the Pixel 6 phone to latest Android 12. It finished running [2022-03-07_mlperfbench_v3.0-alpha5-g.apk](https://drive.google.com/file/d/1ocMxuwzT64UFBN1m7onhWR-7B88QC1Uz/view?usp=sharing), no offline crash

**Comment by anhappdev** [comment] 2022-03-08 06:25
> @anhappdev Tried two apk’s shared in this folder on Samsung S21+ with the Exynos.
> 
> 1. https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0.0-flutter-android-alpha-4 (mlperfbench-v3.0-alpha4-qsmgt.apk). Crashes shortly after the completion of a single/first benchmark
> 2. [Flutter app did not pick up the Samsung backend when built #177 (comment)](https://github.com/mlcommons/mobile_app_open/issues/177#issuecomment-1011790919) (mlperfbench-v3.x-samsung-test-2.apk). IC offline crashes. Other benchmarks work OK.

@fatihcakirs  For Samsung please try this latest build:
https://github.com/mlcommons/mobile_app_open/issues/231#issuecomment-1056769024

**Comment by freedomtan** [comment] 2022-03-08 06:33
We may still need to check the IC offline crash problem. 
@anhappdev a new unified app, with q-s-m-g backends
1. q backend w/ newer SNPE and model path changed (in backend setting code)
2. new Exynos backend (and new model path)
3. pixel backend for v 2.0 submission

**Comment by ptt2panda** [comment] 2022-03-09 05:51
Sorry for the delay, verified that pixel backend works as expected with the app provided above.

**Comment by anhappdev** [comment] 2022-03-14 11:45
It looks like the changes in `submission-v2.0` branch resolve many crashes reported here. I would delay this task until `submission-v2.0` is merged into master, then create a new build from it.

**Comment by anhappdev** [comment] 2022-03-15 09:03
@fatihcakirs I tried to build the Flutter app for Samsung with newer Exynos backend using this branch
https://github.com/mlcommons/mobile_back_samsung/tree/v2_0
but it failed with this error:
```
cp: cannot stat '/mnt/samsung_backend/libeden_model.so': No such file or directory
cp: cannot stat '/mnt/samsung_backend/libeden_profiler.so': No such file or directory
cp: cannot stat '/mnt/samsung_backend/libeden_rt.so': No such file or directory
cp: cannot stat '/mnt/samsung_backend/libeden_ud_gpu.so': No such file or directory
...
cp: cannot stat '/mnt/samsung_backend/libgpu_boost_vendor.so': No such file or directory
cp: cannot stat '/mnt/samsung_backend/libprocessgroup.so': No such file or directory
cp: cannot stat '/mnt/samsung_backend/libvendor_samsung_slsi_hardware_gpu_boost.so': No such file or directory
make: *** [flutter/android.mk:85: flutter/android/libs] Error 1
make: *** [flutter/android.mk:66: docker/flutter/android/apk] Error 2
```

**Comment by d-uzlov** [comment] 2022-03-15 09:16
@anhappdev this issue is caused by our makefile script:
https://github.com/mlcommons/mobile_app_open/blob/639b6dcffbf2f3662fa8ba99547afb94f20d2855/mobile_back_samsung/samsung_backend.mk#L28-L47
It seems to me like you have specified incorrect `MOBILE_BACK_SAMSUNG_LIB_ROOT` env. It should point to the folder where actual `.so` files are located, not to the repository root.

Also, new version of the backend is may have different dependencies, so you may have to adjust list of `.so` files to copy.

**Comment by anhappdev** [comment] 2022-03-15 09:22
@d-uzlov Ok. I thought the vendor is responsible to modify that Makefile, since only they know which `.so` files is needed.
The `MOBILE_BACK_SAMSUNG_LIB_ROOT` is already correct, the folder just miss those files.

**Comment by anhappdev** [comment] 2022-03-16 02:19
> We may still need to check the IC offline crash problem.
@anhappdev a new unified app, with q-s-m-g backends
> 1. q backend w/ newer SNPE and model path changed (in backend setting code)
> 1. new Exynos backend (and new model path)
> 1. pixel backend for v 2.0 submission

This Flutter APK is built by applying all patches for submission v2.0
[2022-03-16_mlperfbench_v3.0-alpha6-qsmgt.apk](https://drive.google.com/file/d/1rKevEeI4rl5KaEM685RqbHCU-9_az3Pv/view?usp=sharing)


Notes:
- Models path are modified to point to `app:///mlperf_models/` directory, that means the files need to be copied to `/Android/data/org.mlcommons.android.mlperfbench/files/mlperf_models/` (see [here](https://github.com/mlcommons/mobile_app_open/blob/master/flutter/documentation/custom-tasks.md#using-external-resources-on-an-android))
- QTI: snpe-1.59.1.3230
- Samsung: sbe_backend
- tensorflow-2.8.0

**Comment by freedomtan** [comment] 2022-03-16 03:13
FYR. I tested on alpha6. It seems to be fine on devices . No crashes.

* tested devices: Oppo Reno 6 Pro (Color OS V11.3, MediaTek Dimensity 1200), MTK internal dev board, Xiaomi Mi11 (MIUI 13.0 Stable 13.0.5.0 (SKBCNXM), Qualcomm 888), Pixe 4, Pixel 6

**Comment by freedomtan** [comment] 2022-03-22 05:08
@fatihcakirs and Samsung colleagues are going to check it. Let's try to close this by next week.

**Comment by freedomtan** [comment] 2022-03-29 05:17
Let's wait for Samsung's local test.

**Comment by freedomtan** [comment] 2022-04-05 05:08
it seems that the samsung backend is not correctly picked up (falling to the tflite backend). @fatihcakirs will check it again.

**Comment by freedomtan** [comment] 2022-04-19 05:42
@fatihcakirs will help to get the flutter app correctly detect Samsung backend

**Comment by fatihcakirs** [comment] 2022-04-26 05:09
@anhappdev Can you check [this branch](https://github.com/mlcommons/mobile_back_samsung/tree/v2.0-flutter). In particular, please consider the [mobile_back_samsung](https://github.com/mlcommons/mobile_back_samsung/tree/v2.0-flutter/mobile_back_samsung) folder for the backend files and [update.sh](https://github.com/mlcommons/mobile_back_samsung/blob/v2.0-flutter/flutter/update.sh). These two contain the necessary changes to build the flutter app with the Exynos backend supported.

**Comment by anhappdev** [comment] 2022-04-27 01:15
@fatihcakirs Can you provide more context? How should I build the app? For example the [update.sh](https://github.com/mlcommons/mobile_back_samsung/blob/v2.0-flutter/flutter/update.sh) has this line
`cd ../../mlperf_backend/sbe_backend/jni` 
but I don't see any `mlperf_backend` folder in the repo.

**Comment by fatihcakirs** [comment] 2022-04-27 19:32
Thank you Ahn, let me email you.

**Comment by freedomtan** [comment] 2022-05-03 05:26
related to #292, supposedly if #292 is resolved, this is resolved too.

**Comment by freedomtan** [comment] 2022-05-31 05:14
it seems to close this for now.

**Closed by freedomtan** 2022-05-31 05:14 UTC
Labels: pri 1, 2.1
