### ISSUE TITLE
master fails to build on windows

### ISSUE THREAD

**Issue by mkankana** [mlcommons/mobile_app_open#441] opened 2022-07-15 19:25 UTC
Flutter build on windows fails with master branch ( commit ID test : 52aca2a28043d5b1df9b5eca9ebe537404498a4a)

``` 
git clone https://github.com/mlcommons/mobile_app_open.git
cd mobile_app_open
make flutter 

``` 

ERROR: C:/users/mkankana/_bazel_mkankana/4gqmzekv/external/build_bazel_rules_apple/apple/internal/partials/resources.bzl:235:5: nested functions are not allowed. Move the function to the top level.
ERROR: Skipping '//flutter/cpp/flutter:backend_bridge.dll': error loading package 'flutter/cpp/flutter': in C:/users/mkankana/_bazel_mkankana/4gqmzekv/external/build_bazel_rules_apple/apple/apple.bzl: in C:/users/mkankana/_bazel_mkankana/4gqmzekv/external/build_bazel_rules_apple/apple/internal/xcframework_rules.bzl: in C:/users/mkankana/_bazel_mkankana/4gqmzekv/external/build_bazel_rules_apple/apple/internal/partials.bzl: Extension 'apple/internal/partials/resources.bzl' has errors
ERROR: error loading package 'flutter/cpp/flutter': in C:/users/mkankana/_bazel_mkankana/4gqmzekv/external/build_bazel_rules_apple/apple/apple.bzl: in C:/users/mkankana/_bazel_mkankana/4gqmzekv/external/build_bazel_rules_apple/apple/internal/xcframework_rules.bzl: in C:/users/mkankana/_bazel_mkankana/4gqmzekv/external/build_bazel_rules_apple/apple/internal/partials.bzl: Extension 'apple/internal/partials/resources.bzl' has errors
INFO: Elapsed time: 572.376s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: mobile_back_tflite/cpp/backend_tflite
    Fetching @local_config_cuda; fetching
    Fetching @bazel_skylib; fetching
    Fetching @build_bazel_rules_swift; fetching
make: *** [flutter/windows/windows.mk:24: flutter/windows/libs] Error 1

**Comment by freedomtan** [comment] 2022-07-19 01:58
@anhappdev and @d-uzlov  it seems we have to avoid including apple specific rules on other platforms.

**Comment by anhappdev** [comment] 2022-07-19 02:42
The CI test for Windows `Build-and-test-Flutter-Windows-PR`:
- was successful for the PR branch before merge
- but failed on the master branch after merge

because the code base of the 2 test was different.

But the CI test failed at running integration test, the build test was successful.

```
Running IC_tpu_float32 in performance_lite_mode mode...
Benchmark result: id: IC_tpu_float32, RunResult(throughput:8.270696713061874, accuracy:0.00%), elapsed: 0:00:00.780968
Running OD_float32 in performance_lite_mode mode...
Benchmark result: id: OD_float32, RunResult(throughput:5.762795237076468, accuracy:0.0000 mAP), elapsed: 0:00:01.256659
Running IS_float32_mosaic in performance_lite_mode mode...
Benchmark result: id: IS_float32_mosaic, RunResult(throughput:2.5281285938534563, accuracy:N/A), elapsed: 0:00:03.073745
Running LU_float32 in performance_lite_mode mode...
Benchmark result: id: LU_float32, RunResult(throughput:1.264317719091815, accuracy:50.0000), elapsed: 0:00:06.224666
Running IC_tpu_float32_offline in performance_lite_mode mode...
make[1]: *** [flutter/flutter.mk:167: flutter/test] Error 1
make: *** [flutter/windows/windows-docker.mk:43: flutter/windows/ci] Error 2
Benchmark result: id: IC_tpu_float32_offline, RunResult(throughput:14.556836766674582, accuracy:0.00%), elapsed: 0:00:00.674533
Benchmarks finished
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building ProgressScreen(dirty, dependencies:
[_LocalizationsScope-[GlobalKey#a82d6], _InheritedProviderScope<BenchmarkState?>], state:
_ProgressScreenState#6bb15):
Unsupported operation: Infinity or NaN toInt
```

So I guess the issue is the different between build environment of the CI machine and @mkankana's machine

**Comment by freedomtan** [comment] 2022-08-30 05:22
let's close this for now.

**Closed by freedomtan** 2022-08-30 05:22 UTC
Labels: pri 2, 3.0
