### ISSUE TITLE
Add filters to online results list

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#490] opened 2022-08-29 08:18 UTC
We need to add a button for search/filtering of online results, and modify firebase functions API to support it.

Child tasks:
1. Add filtering by OS type
    * https://github.com/mlcommons/mobile_app_open/issues/505
2. Add filtering by backend
    * https://github.com/mlcommons/mobile_app_open/issues/506
3. Add filtering by date
    * https://github.com/mlcommons/mobile_app_open/issues/546
    * Only available when sorting by date
4. Add filtering by manufacturer
    * https://github.com/mlcommons/mobile_app_open/issues/542
    * You can only choose one
    * Also need to maintain a list of known manufacturers
5. Add filtering by exact device model
    * https://github.com/mlcommons/mobile_app_open/issues/543
    * You can only choose one
    * Also need to maintain a list of known models
6. Add filtering by SoC/CPU
    * https://github.com/mlcommons/mobile_app_open/issues/547
    * You can only choose one
    * Also need to maintain a list of known models

We may need to cut some of the filters because of the Firebase limitations.

**Comment by d-uzlov** [comment] 2022-10-11 04:37
### Firebase limitations

* Support for logical operators `OR` and `!=` is very limited
  * `OR` is only possible once per query and is limited by 10 values in one array field
  * `!=` is only possible once per query
  * `OR` and `!=` are mutually exclusive
* You need to create an index for everything
  * At the very least you need a special index for each queried field and for each sorting option
  * We need 8 possible sorting options: `newest first`, `oldest first`, and 6 `fastest <task> first` (now we have 5 tasks but we expect to add a new one for super resolution)
    * For each field that we add we must add 8 indices
  * Total number of indices is limited by 200
  * It's possible to create indices programmatically

### What this means for us

* Filters of type "select X values from Y possible values" are _generally_ forbidden
  * You can still create such filters provided the number of possible values is known beforehand and is small enough
    * I tried doing this for `OS type` filter, where we only have 3 values
* `Manufacturer`, `Model`, `SoC/CPU` filters must be of type "Select one value from Y possible values"
* We may have up to 25 indexed fields
  * If we add more sorting options this number will decrease
    *  Adding a new task adds a sorting option
  * "select 1 from Y" filter adds 1 indexed field
  * "select X from N" filter adds N indexed fields

**Comment by freedomtan** [comment] 2022-10-11 05:55
@mkankana for your information, the limitation of Firebase

**Comment by d-uzlov** [comment] 2022-10-11 09:35
> * We may have up to 25 indexed fields

If we want to update our database scheme without killing old version(s) of the app, we will also need to keep indices for several database schemes. Alternatively we will need to create several Firebase projects.

**Comment by freedomtan** [comment] 2022-10-18 05:31
1. mostly we are destined to run into the limitations of Firebase, so we need an alternative.
2. we need either NoSQL, such as MongoDB, or embedded SQL, such as sqlite. Please add some more information of available either NoSQL or SQL DB services.

**Comment by anhappdev** [comment] 2022-10-18 06:04
I case we need to change to another DB, we should also think about this related issue https://github.com/mlcommons/mobile_app_open/issues/550 at the same time. 
So we actually need a local DB for storing benchmark results and an online DB for storing uploaded results. It would be beneficial to have both local and online DB of the same type.

I have worked a lot with DB, so here are some of my thoughts:
1. We should use a DB as a service for the online DB since maintaining a DB server requires great effort.
2. I, personally, would choose SQL over NoSQL because querying with SQL is standardized, and many developers should already be familiar with it. My favorite choice is PostgreSQL.
3. Either NoSQL or SQL, we should always think carefully about the DB schema.

**Comment by freedomtan** [comment] 2022-10-19 06:46
A fully-fledge DB on mobile devices sounds weird to me, that's why I mentioned embedded DB such as sqlite, which is supported by Android and iOS. I don't know how hard it is to have sqlite on google cloud, though.

**Comment by anhappdev** [comment] 2022-10-19 08:23
> It would be beneficial to have both local and online DB of the same type.

With the same type I mean either SQL or NoSQL. If PostgreSQL is for the server (the online DB), then the client can use SQLite (the local DB).

I never tried to use SQLite on the server-side. I think it's better to use one of the available managed databases (e.g. on [Google Cloud](https://cloud.google.com/products/databases)).

**Comment by d-uzlov** [comment] 2022-10-19 08:51
SQL is available as a service in GCP, including PostgreSQL.

NoSQL options in GCP are Firestore and Bigtable.
We already know that Firestore doesn't fit our needs.
Bigtable is a low level database, it seems to be oriented toward streams of data, so it also wouldn't work for us.

GCP also has a partnership with other services.
Particularly there are MongoDB Atlas and Elastic Cloud, which provide MongoDB and ElasticSearch as a service respectively.
I'm not sure how deep the integration is, but the billing will be through GCP.

**Comment by d-uzlov** [comment] 2022-10-19 08:52
> It would be beneficial to have both local and online DB of the same type.

I don't think we would really benefit from it.

We have very different needs for local and for online results.

---

Requirements for online results:

* Ability to add a new entry
* List entries
* Sort results by time or score
* Filter sorted results via several criteria
* Handle pagination
* Handle 1000s of entries in the near future, and handle possibly 100k+ in far future

---

Requirements for local results:

* Ability to add a new entry
* Ability to delete an entry
* List all entries
* _Maybe_ sort entries by creation time or by score in different benchmarks
* Handle 1000s entries in the worst case. End users will most likely have no more than 100 entries, and developers will maybe have 1000s

Most of the filters are just invalid for local results. OS and hardware is not expected to change on a device.
Even if we decide to add some sort and filters for local results, the amount of entries in the history is small enough to load everything into memory and sort/filter them manually without performance concerns.

Right now we use JSON with a list of results as a kind "database" for local results, and it works fine.  
The reason to have a proper database for local history is to avoid rewriting megabytes of data on disk each time when we add or delete a result, and also I don't really like the fact that user can open the text file and edit anything.

Also we use different languages in the app and on the server side. Even if we use the same database, we will need to have different libraries to access the database and different bindings to data classes.

So, overall, I don't think our local database should affect our server-side database in any way.

**Comment by d-uzlov** [comment] 2022-10-19 08:52
Our data structure is a document in a form of JSON.
We don't need to modify these documents after they are generated, but we do need to read some of the values in them for filtering and sorting.

So, our database for results must support the following:
1. List results
2. Filter and sort results based on several selected fields
3. Return source data

In SQL implementation would look like this:
One table.
Several columns, one for each of the required filters.
One column with serialized JSON.

But also the same scheme will work for NoSQL databases, except JSON serialization may be optional.

We don't need any of the SQL advanced features, we only need to search within a single table. So a NoSQL solution would work fine.
We also don't expect to have millions of users accessing the database at the same time, so I guess we shouldn't face any performance issues with SQL.

**Comment by anhappdev** [comment] 2022-10-19 09:12
I prefer that both local results and online results sharing the same code and the same UI, maybe with the only different is a boolean flag "isLocalResult". So reusing UI elements and querying logic would be a big benefit. So, it should use the same type of DB.

**Comment by freedomtan** [comment] 2022-10-25 05:04
in the old days when I learned to use DB on PCs decades ago. There is something called ODBC, which was intended to serve as a universal API to all relational DBs. Do we have something like for Flutter.

**Comment by anhappdev** [comment] 2022-10-25 06:05
Another solution as mentioned in the meeting:

If the number of results is not big, we can just query all the results from Firebase then do the filtering locally on-device using the Dart programming language. So we can still use Firebase for now and have the feature with the least effort.

Later if the data grows big enough, we can transition to use another solution which is suitable for large-scale data (which requires much more effort to design and implement). The existing data from Firebase will be imported to the new DB.

**Comment by anhappdev** [comment] 2023-01-22 14:40
Closing this in favor of https://github.com/mlcommons/mobile_app_open/issues/641

**Closed by anhappdev** 2023-01-22 14:40 UTC
Labels: meta:help-wanted, priority:high, release:3.0, size:big, domain:results
