### ISSUE TITLE
Improve performance of Core ML backend

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#472] opened 2022-08-04 03:55 UTC
We have just implemented the Core ML backend, the focus was to make it work first, then make it work faster.
The performance of the Core ML backend should be equal or better than TFLite backend.

**Comment by freedomtan** [comment] 2022-08-07 10:40
I did some profiling. One of the reasons why there is performance gap is that, no surprise, some kind of thermal throttling. My observation, for Mobilenet EdgeTPU on iPhone 13, we can see for first tens inferences, the Neural Engine Prediction time, although not as good as M1's ~ 0.46 ms, it's 0.5 ~ 0.6 ms. But it jumps to around 1.2 ms.   I don't really know how to reduce this kind problem legitimately with MLPerf submission rules. Of course, there are other overheads.

**Comment by freedomtan** [comment] 2022-08-13 05:49
@anhappdev and @d-uzlov  for your reference, I did further observations of Mobilenet EdgeTPU. It seems it's scheduling policy, not thermal thermal throttling. When I did a cold start, thermal state shown by the Instruments seems to be fine (always Nominal for the 60 s running time), but the Neural Engine Prediction time increases very soon (from 0.5x ms to > 1 ms). If I set the qos class to  be `utility` by adding `pthread_set_qos_class_self_np(QOS_CLASS_UTILITY,0);`. The prediction time started 0.8x ms instead of 0.5x ms. 


No, I don't know how to fix it (yet).

**Comment by anhappdev** [comment] 2022-08-13 14:33
In the past, I did observe that we can get much better throughput by adding a simple loop `while true { let a = 1 + 1 }` to the app when running benchmark. It looks like that this simple loop keeps the CPU busy and prevent some energy saving logic kick in. But it's a hack so I am uncertain if we can use it.

**Comment by freedomtan** [comment] 2022-08-16 08:16
@anhappdev please check if the artificial load (`while true { let a = 1 + 1 }`) works for the Core ML backend.

**Comment by anhappdev** [comment] 2022-08-16 09:22
It looks like that the artificial load hack does not increase the throughput anymore with current implementation.
But compared to the past result here https://github.com/mlcommons/mobile_app_flutter/issues/198#issuecomment-898865768 I already get similar result with the current Core ML backend. So we need to find other solutions.

**Comment by anhappdev** [comment] 2022-08-17 12:15
I did some analysis. Most of the time which is relevant for the benchmark is spent on `mlperf_backend_issue_query` as expected.

<img width="651" alt="Screenshot 2022-08-17 at 19 05 25" src="https://user-images.githubusercontent.com/85728587/185114145-4ae4d8b4-4fba-483b-a743-a2c9bc6dfe58.png">

The time it takes to prepare input data and process output data is minimal, so no big potential to optimize it. Most of the time is spent in `[MLModel predictionsFromBatch:error:]`.

<img width="792" alt="Screenshot 2022-08-17 at 19 07 33" src="https://user-images.githubusercontent.com/85728587/185114550-a2d16acd-fbb0-4815-95a9-e0fa8f35a317.png">

I did try to use the method [[predictionFromFeatures:options:error](https://developer.apple.com/documentation/coreml/mlcustommodel/2994297-predictionfromfeatures?changes=_5_3&language=objc)] for Single Stream scenario but no improvement as expected because `predictionsFromBatch:options:error:` just calls `predictionFromFeatures:options:error`.

Here is the trace file for reference: [MLPerf_CoreMLBackend.trace.zip](https://github.com/mlcommons/mobile_app_open/files/9359363/MLPerf_CoreMLBackend.trace.zip)

@freedomtan I am out of idea what to try to increase the throughput. Do you have any idea?

**Comment by freedomtan** [comment] 2022-08-17 13:45
Some ideas for your reference
1. Profiling with Core ML template or (manually adding Neural Engine and Core ML profiling): you can see maybe we can try to improve either `Neural Engine Prediction` time or output target (ANE) to host (ARM) memory copy time. 
2. Check what we can get by using DTrace CLPC probes (`sudo dtrace -l | grep CLPC`). It seems Apple's DVFS is controlled by Closed-Loop Performance Controller (CLPC) and there are some ANE related probes in CLPC. Maybe we can get some information
3. Reverse-engineering / disassembling CPLC (`/System/Library/Extensions/AppleT8103CLPCv3.kext/Contents/MacOS/AppleT8103CLPCv3` on macOS 12.x or Kernel Debug Kit (KDK) on macOS 13.x) to see if we can find useful information. [Ghidra](https://ghidra-sre.org/) could disassemble and decompile (translate assembly to C/C++ to some extent)  macOS/iOS binaries

**Comment by anhappdev** [comment] 2022-08-18 11:48
I compared the mean latency reported by the app with the mean latency from XCode performance report and see almost the same numbers so I think the code should be good for now. I switch my focus to optimizing the model itself.

I converted the models to the new [`ML Program`](https://coremltools.readme.io/docs/ml-programs) model type (currently is `Neural Network`) and got some improvement:
- `Mosaic`: QPS increased from 12 to 17 
- `MobileBERT`: QPS increased from 9 to 25 but accuracy droped from 95 to 23
- `MobilenetEdgeTPU`: has no improvement.
- `MobileDet`: still not able to convert to `ML Program` yet because we use `NeuralNetworkBuilder` in conversion script.

The caution is that `ML Program` is supported first in iOS 15.0.

Here is the new converted models: https://github.com/mlcommons/mobile_models/tree/coremlpackage/beta/CoreML
The update scripts are here: https://github.com/mlcommons/mobile_app_open/pull/481

**Comment by anhappdev** [comment] 2022-08-19 01:33
Yes, indeed. I wonder why. 

<img width="1079" alt="Screenshot 2022-08-19 at 08 03 23" src="https://user-images.githubusercontent.com/85728587/185522399-7d9fedd5-8354-4b4b-bb67-34bd53fd83cc.png">

```
================================================
MLPerf Results Summary
================================================
SUT name : Core ML
Scenario : SingleStream
Mode     : PerformanceOnly
90th percentile latency (ns) : 1790000
Result is : VALID
  Min duration satisfied : Yes
  Min queries satisfied : Yes

================================================
Additional Stats
================================================
QPS w/ loadgen overhead         : 575.09
QPS w/o loadgen overhead        : 575.70

Min latency (ns)                : 1377417
Max latency (ns)                : 3008750
Mean latency (ns)               : 1737005
50.00 percentile latency (ns)   : 1733708
90.00 percentile latency (ns)   : 1790000
95.00 percentile latency (ns)   : 1808334
97.00 percentile latency (ns)   : 1821667
99.00 percentile latency (ns)   : 1859333
99.90 percentile latency (ns)   : 2043958

================================================
Test Parameters Used
================================================
samples_per_query : 1
target_qps : 1000
target_latency (ns): 0
max_async_queries : 1
min_duration (ms): 60000
max_duration (ms): 0
min_query_count : 1024
max_query_count : 0
qsl_rng_seed : 6655344265603136530
sample_index_rng_seed : 15863379492028895792
schedule_rng_seed : 12662793979680847247
accuracy_log_rng_seed : 0
accuracy_log_probability : 0
accuracy_log_sampling_target : 0
print_timestamps : 0
performance_issue_unique : 0
performance_issue_same : 0
performance_issue_same_index : 0
performance_sample_count : 830

No warnings encountered during test.
```

Noted that the XCode performance report uses median (50th percentile) while the app uses 90th percentile.

**Comment by freedomtan** [comment] 2022-08-19 02:00
> Yes, indeed. I wonder why.
> 
> <img alt="Screenshot 2022-08-19 at 08 03 23" width="1079" src="https://user-images.githubusercontent.com/85728587/185522399-7d9fedd5-8354-4b4b-bb67-34bd53fd83cc.png">
> 
> ```
> ================================================
> MLPerf Results Summary
> ================================================
> SUT name : Core ML
> Scenario : SingleStream
> Mode     : PerformanceOnly
> 90th percentile latency (ns) : 1790000
> Result is : VALID
>   Min duration satisfied : Yes
>   Min queries satisfied : Yes
> 
> ================================================
> Additional Stats
> ================================================
> QPS w/ loadgen overhead         : 575.09
> QPS w/o loadgen overhead        : 575.70
> 
> Min latency (ns)                : 1377417
> Max latency (ns)                : 3008750
> Mean latency (ns)               : 1737005
> 50.00 percentile latency (ns)   : 1733708
> 90.00 percentile latency (ns)   : 1790000
> 95.00 percentile latency (ns)   : 1808334
> 97.00 percentile latency (ns)   : 1821667
> 99.00 percentile latency (ns)   : 1859333
> 99.90 percentile latency (ns)   : 2043958
> 
> ================================================
> Test Parameters Used
> ================================================
> samples_per_query : 1
> target_qps : 1000
> target_latency (ns): 0
> max_async_queries : 1
> min_duration (ms): 60000
> max_duration (ms): 0
> min_query_count : 1024
> max_query_count : 0
> qsl_rng_seed : 6655344265603136530
> sample_index_rng_seed : 15863379492028895792
> schedule_rng_seed : 12662793979680847247
> accuracy_log_rng_seed : 0
> accuracy_log_probability : 0
> accuracy_log_sampling_target : 0
> print_timestamps : 0
> performance_issue_unique : 0
> performance_issue_same : 0
> performance_issue_same_index : 0
> performance_sample_count : 830
> 
> No warnings encountered during test.
> ```
> 
> Noted that the XCode performance report uses median (50th percentile) while the app uses 90th percentile.

Ha, the iPad Pro you tested uses Apple A13 or older SoC. There are significant transpose and context switch overheads on CPU. On A14 and A15 devices (iPhone 12 and later), all MobileNet EdgeTPU ops are on ANE. It seems there is some hardware problems so that newer iOS and Core ML software stack can make MOSAIC and MobileBERT work well on chips older than A14/M1.

On iPhone 11 Pro (A13),  if you check MobileBERT and MOSAIC with Xcode Core ML model performance, you can see MOSAIC is chopped into several subgraphs and only about half of the subgraphs are on ANE. For MobileBERT, ANE is not used all.

**Comment by anhappdev** [comment] 2022-08-19 02:17
Ok. The MobileBERT and MOSAIC low performance is hardware related.

> I saw significant performance gaps between Xcode model performance and the App on iPhone 13.

But I am most wondering why the Xcode performance report on iPhone 13 has much better number than the app, while on my iPad I got almost the same number (for all models, BTW).

**Comment by freedomtan** [comment] 2022-08-19 02:31
> Ok. The MobileBERT and MOSAIC low performance is hardware related.
> 
> > I saw significant performance gaps between Xcode model performance and the App on iPhone 13.
> 
> But I am most wondering why the Xcode performance report on iPhone 13 has much better number than the app, while on my iPad I got almost the same number (for all models, BTW).

My guess is that it's related to CPU load tracking and DVFS mechanisms. Why "artificial load" trick works for some cases is that it seems

1. the ANE frequency is kinda associated with CPU DVFS
2. when we can offload most ops to ANE, CPU load is relatively low, so ANE slows down also
3. when there are more CPU activities involved, e.g., your iPad, CPU load is kept higher

That's my theory (based on some observations). I tried to figure out how iPhone/iPad DVFS works before (before M1) without success.

**Comment by anhappdev** [comment] 2022-08-19 06:17
I mean on your iPhone 13, the Xcode performance report shows a lower mean latency for `MobileNetEdgeTPU` compared to the app. But on my iPad the 2 numbers are almost the same.

So I was wondering why the app and Xcode have similar numbers on iPad, but not on iPhone 13?
Is there something code related? Then, if it's hardware related, the app should get the same number as Xcode performance report for iPhone 13.

**Comment by freedomtan** [comment] 2022-08-19 06:25
> I mean on your iPhone 13, the Xcode performance report shows a lower mean latency for `MobileNetEdgeTPU` compared to the app. But on my iPad the 2 numbers are almost the same.
> 
> So I was wondering why the app and Xcode have similar numbers on iPad, but not on iPhone 13? Is there something code related? Then, if it's hardware related, the app should get the same number as Xcode performance report for iPhone 13.

Yes, I was explaining my observations on that. On the iPhone 13, all the Mobilenet EdgeTPU ops were offloaded to ANE; on your iPad there were some more CPU loads because not all ops were offloaded  to ANE (thus it has higher CPU load).

**Comment by freedomtan** [comment] 2022-08-19 23:55
The first 100 inferences in the figure below are relatively close to Xcode model performance numbers,
<img width="200" alt="Screen Shot 2022-08-20 at 7 04 04 AM" src="https://user-images.githubusercontent.com/3395998/185720306-581246e6-10fe-458a-9e4a-b4af5e89dcc6.png">

One of the interesting things to note is that LITTLE (efficient) cores are not used for the first 200+ milliseconds.
 
<img width="200" alt="Screen Shot 2022-08-20 at 7 06 59 AM" src="https://user-images.githubusercontent.com/3395998/185720494-202f9828-2a21-4361-a7b6-537489f24df9.png">

Traces when running the MobileNet EdgeTPU with the app on iPhone 13,
[take 1](https://drive.google.com/file/d/1Q_2z6fofMiioq-qfwHrSl4-Fm1w7dvKz/view?usp=sharing)
[task 2](https://drive.google.com/file/d/16eaWqEm8V7y4IjUeLp2H6qUrMPMwHBwn/view?usp=sharing)

**Comment by anhappdev** [comment] 2022-08-23 04:43
For now, one improvement we can make is that using the new [ML Program](https://coremltools.readme.io/docs/ml-programs) model type but it requires iOS 15+. Should we make that change? iOS 15 can be installed on almost all iPhones from 2016 (https://support.apple.com/en-vn/guide/iphone/iphe3fa5df43/ios).

**Comment by freedomtan** [comment] 2022-08-23 04:57
> For now, one improvement we can make is that using the new [ML Program](https://coremltools.readme.io/docs/ml-programs) model type but it requires iOS 15+. Should we make that change? iOS 15 can be installed on almost all iPhones from 2016 (https://support.apple.com/en-vn/guide/iphone/iphe3fa5df43/ios).

Let me check if I can get better numbers on iPhone 13 and M1.

**Comment by anhappdev** [comment] 2022-08-23 07:55
> MobileBERT: QPS increased from 9 to 25 but accuracy droped from 95 to 23

By setting `compute_precision=ct.precision.FLOAT32` when converting, the model produces expected accuracy on my iPad (0.96). The throughput drops a bit though (now 17) but still better than the `.mlmodel` one.

**Comment by freedomtan** [comment] 2022-08-23 23:16
> > For now, one improvement we can make is that using the new [ML Program](https://coremltools.readme.io/docs/ml-programs) model type but it requires iOS 15+. Should we make that change? iOS 15 can be installed on almost all iPhones from 2016 (https://support.apple.com/en-vn/guide/iphone/iphe3fa5df43/ios).
> 
> Let me check if I can get better numbers on iPhone 13 and M1.

@anhappdev bad news. Quick check shows that there is performance degrade on iPhone 13 and M1 instead of improvement.

MobileNet EdgeTPU: roughly the same as .mlmodel
MOSAIC:  partition into several subgraphs, back-and-forth between ANE and CPU, 
MobileBERT: CPU + GPU no ANE.

You can easily verify these with Xcode 14 beta model performance on M1 machines.
![Screen Shot 2022-08-24 at 7 14 15 AM](https://user-images.githubusercontent.com/3395998/186282173-0f899ab2-1bf7-41a4-8ea7-e7e4c76afd11.png)

**Comment by anhappdev** [comment] 2022-08-24 05:41
@freedomtan 
1. For `MobileBERT`, did you run the `.mlmodel` in accuracy mode? I guess that the accuracy will be low because on my test if the `MobileBERT` model is (partially) executed on the ANE, the accuracy is low. Therefore, the new `.mlpackage` file is converted with the option `compute_precision=ct.precision.FLOAT32`.
2. For `Mosaic`, the number is a bit lower (71 here vs. 98 [in the last comment](https://github.com/mlcommons/mobile_app_open/issues/472#issuecomment-1219633506)), but can it be related to the Debug build vs. a Release / Profile build (to be recognized by the red DEBUG text in the top-right corner)?
3. Per the description of [Comparing ML Programs and Neural Networks](https://coremltools.readme.io/docs/comparing-ml-programs-and-neural-networks) we should expect that the new `MLProgram` in general provides better performance. I will research more on this matter.

**Comment by anhappdev** [comment] 2022-08-24 07:17
Indeed, for `Mosaic` I got lower number on Mac M1, but higher number for iPad Pro using the new `MLProgram` format.
It looks like we should focus on one certain device and optimize for it first.

**Comment by freedomtan** [comment] 2022-08-24 09:58
> @freedomtan
> 
> 1. For `MobileBERT`, did you run the `.mlmodel` in accuracy mode? I guess that the accuracy will be low because on my test if the `MobileBERT` model is (partially) executed on the ANE, the accuracy is low. Therefore, the new `.mlpackage` file is converted with the option `compute_precision=ct.precision.FLOAT32`.

That was using float16. We know the software and / or hardware of ANE float16 is faulty (when we were still  converting models and testing with the command line program.

ANE doesn't support float32, and so far, all the mobile NN accelerators don't either (most of them support quanized int8/uint8 + fp16 and/or bf16). Comparing fp32 performance would be weird. Let's assume this will be fixed in Apple's upcoming A16 SoC :-)

> 3. Per the description of [Comparing ML Programs and Neural Networks](https://coremltools.readme.io/docs/comparing-ml-programs-and-neural-networks) we should expect that the new `MLProgram` in general provides better performance. I will research more on this matter.

IMO, ideally, we should avoid fp32, so the fp32 in GPU is kinda irrelevant. And for compiling time, yes, it looks great, but we don't count compiling time :-)

**Comment by freedomtan** [comment] 2022-08-29 13:08
FYR, numbers I got with recent beta
software | version
-- | --
iOS 16 | beta 7
macOS 13 | beta 6
Xcode 14 | beta 6
mobile_app_ope | 

device | Image Classification | Object Detection | Image Segmentation | Language Understanding | Image Classification (offline)
-- | --: | --: | --: | --: | --:
Macbook Pro M1 App | 1122.23 | 613.75 | 114.39 | 125.38 | 2193.12
Macbook Pro M1 Xcode model perf | 1282.05 | 675.68 | 124.53 | 127.88 | N/A
iPhone 13 App | 531.93 | 356.58 | 78.86 | 90.65 | 1307.30
iPhone 13 Xcode model perf | 990.10 | 537.63 | 110.99 | 103.84 | N/A

**Comment by freedomtan** [comment] 2022-08-30 06:13
To answer @anhappdev's question for task affinity and load tracking on Android devices. Yes, we also have this kind of problems, but, fortunately, there is public api (https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html)  and command line tool (taskset, https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark#reducing-variance-between-runs-on-android) to set task affinity. And, usually, SoC vendors provide different API to boost CPU performance so that we can get expected performance numbers.

**Comment by freedomtan** [comment] 2022-08-31 14:53
@anhappdev and @mkankana quick test shows that adding artificial loads works for Image Classification (531.93 -> 744.33) and Object Detection (356.58 -> 449.37) on iPhone 13. Most of the time, with the artificial loads I added, big cores are used most of the time. Now, the problem is how to add appropriate loads. With continuous computation on CPU(s), it's easy to run into thermal wall as @Mostelk mentioned :-)

**Comment by freedomtan** [comment] 2022-08-31 22:19
FYI, a round with my naIve artificial load

<img width="200" alt="Screen Shot 2022-09-01 at 6 13 17 AM" src="https://user-images.githubusercontent.com/3395998/187795104-624ad17c-dd06-4720-b31e-ccd644829450.png">

**Comment by anhappdev** [comment] 2022-09-05 07:32
On my device iPhone XS, the artificial loads didn't increase the score, but does not decrease it either. Looks like that each device behaves differently. Should we include this in the app?

**Comment by freedomtan** [comment] 2022-09-06 03:05
> On my device iPhone XS, the artificial loads didn't increase the score, but does not decrease it either. Looks like that each device behaves differently. Should we include this in the app?

That's kinda expected. I guess Performance cores are used most of the time (because of fallbacked ops) on iPhone XS already. On the iPhone 11 Pro I loaned from my colleague, I saw CPU loads are Performance cores most of time.

**Comment by anhappdev** [comment] 2022-09-06 03:10
Instead of adding the artificial loads, I think we can also add a CPU only ops to the models to have the same effect?

**Comment by freedomtan** [comment] 2022-09-06 03:57
> Instead of adding the artificial loads, I think we can also add a CPU only ops to the models to have the same effect?

theoretically, yes. I don't know how to do it properly, though

**Comment by freedomtan** [comment] 2022-09-07 06:25
# why `QOS_CLASS_UTILITY`  will place a thread on efficient cluster(s)
As I mentioned before, `pthread_set_qos_class_self_np(QOS_CLASS_UTILITY, 0);` is likely to put threads on efficient clusters. But why? When I was checking if it's possible to force threads to run on performance cluster(s), I read through some macOS kernel source code and found that,

- On M1 machines, the scheduler in use is the Edge scheduler, https://github.com/apple-oss-distributions/xnu/blob/xnu-8020.140.41/doc/sched_clutch_edge.md
 - For the Edge scheduler, according to https://github.com/apple-oss-distributions/xnu/blob/xnu-8020.140.41/osfmk/kern/sched_clutch.c#L4996-L5011, if `THREAD_QOS_BACKGROUND` is used, the thread will be run on efficient cluster(s)
 - on iDevices with both p and e clusters, mostly, the scheduler is AMP scheduler
 - according to https://github.com/apple-oss-distributions/xnu/blob/xnu-8020.140.41/osfmk/kern/sched_amp_common.c#L452-L474, if `THREAD_QOS_UTILITY` is used, the thread will be run on efficient cluster(s)

However, **I cannot find any similar clues for placing threads on performance clusters** (yet).

**Comment by freedomtan** [comment] 2022-09-09 08:14
# What doesn't work
Put down things I tried but failed to for threads on performance clusters.

- `pthread_set_qos_class_self_np()` : `QOS_CLASS_USER_INTERACTIVE` [1] doesn't work 
- `pthread_setschedparam()`: setting `SCHED_RR` doesn't work [2] 
- `thread_policy_set()` and `THREAD_TIME_CONSTRAINT_POLICY` [2]:  doesn't work
- `thread_policy_set()` and `THREAD_AFFINITY_POLICY`: setting thread affinity on iPhone and M1 doesn't work as explained in [3]. I checked recent XNU source code and disassemble recent iPhone kernel, still this is not supported.

# What could be tried
- [ ] read Edge and AMP scheduler source code to see if we could there is any clue
- [ ] disassemble CLPCv3 to see if we could find something
- [ ] ??

[1] https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html
[2] https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/KernelProgramming/scheduler/scheduler.html
[3] https://developer.apple.com/forums/thread/703361

**Comment by mkankana** [comment] 2022-09-12 18:08
> FYI, a round with my naïve artificial load
> 
> <img alt="Screen Shot 2022-09-01 at 6 13 17 AM" width="200" src="https://user-images.githubusercontent.com/3395998/187795104-624ad17c-dd06-4720-b31e-ccd644829450.png">

Looks like the artificial load is decreasing performance on segmentation and language models. Should we consider not doing this load for these 2 workloads ?
 
Below is the performance share by @anhappdev without the load.

<img width="216" alt="MLPerf_IOS" src="https://user-images.githubusercontent.com/43794796/189725403-8e5bde0b-5eaf-479c-9b0f-7015490da4a8.png">

**Comment by freedomtan** [comment] 2022-09-13 05:46
Let's add an option to turn on and off artificial load?

**Comment by freedomtan** [comment] 2022-09-14 09:19
# Thread Affinity

The task/thread affinity (to specific processors/cores), or say processor affinity, is tricky on macOS/iOS. Generally, pthread doesn’t have affinity functions. The Linux pthread_{set,get}affinity_np() functions are not standard ones. Consequently, there is no something like the linux taskset could be used. The macOS does have some kind of thread affinity, but it is different from Linux one. See [1] for more information. However, we can use  thread_policy_set() and  thread_policy_get() with flavor == THREAD_AFFINITY_POLICY, as  mentioned in [1], but not on M1 machines. What returned by calling them is 46/KERN_NOT_SUPPORTED. Why?

[1] https://developer.apple.com/library/archive/releasenotes/Performance/RN-AffinityAPI/index.html#//apple_ref/doc/uid/TP40006635-CH1-DontLinkElementID_2

## Userland
```
    % sysctl -a |grep aff
    kern.affinity_sets_enabled: 1
    kern.affinity_sets_mapping: 1
```
It seems affinity set is supported. Let's check kernel side.

## Kernel side

From kernel source, it seems quite clear that these two are enabled by default on macOS.

from https://github.com/apple-oss-distributions/xnu/blob/xnu-8020.140.41/osfmk/kern/affinity.c#L77-L93
```
/*
 * The following globals may be modified by the sysctls
 *   kern.affinity_sets_enabled	- disables hinting if cleared
 *   kern.affinity_sets_mapping	- controls cache distribution policy
 * See bsd/kern_sysctl.c
 *
 * Affinity sets are not used on embedded, which typically only
 * has a single pset, and last-processor affinity is
 * more important than pset affinity.
 */
#if !defined(XNU_TARGET_OS_OSX)
boolean_t       affinity_sets_enabled = FALSE;
int             affinity_sets_mapping = 0;
#else /* !defined(XNU_TARGET_OS_OSX) */
boolean_t       affinity_sets_enabled = TRUE;
int             affinity_sets_mapping = 1;
#endif /* !defined(XNU_TARGET_OS_OSX) */
```

**Comment by mkankana** [comment] 2022-09-14 22:36
**"Artificial CPU Load"**
"Some devices perform better with an additional artificial CPU load during test"

@anhappdev  could you please use the above wording for the toggle button. Could we also keep it "ON" by default .

**Comment by anhappdev** [comment] 2022-09-15 01:37
> use the above wording for the toggle button. Could we also keep it "ON" by default .

Ok. Done.

**Comment by freedomtan** [comment] 2022-09-22 04:01
Good news and bad news. 

A colleague loaned me an iPhone 14 Pro for testing just now. It turned out that we don't need artificial load for iPhone 14 Pro (CPU part of Core ML related stuff is performance cores without artificial). Actually, turning on artificial load increase latency numbers of fully ANE offloaded models.

Good part: it's really an Apple/iOS issue.
Bad part: we had artificial load on by default :-)

**Comment by anhappdev** [comment] 2022-09-22 04:33
Should we publish a new build without the artificial load? Or make it off by default?

**Comment by freedomtan** [comment] 2022-09-22 04:46
Removing artificial load, NO, I tested iPhone 13 w/ iOS 16.0 again. We still need artificial load for some devices.
making it off by default, maybe.

**Comment by freedomtan** [comment] 2022-09-27 02:34
FYR, I updated my iPhone 13 to iOS 16.1 beta 2, it's interesting that, unlike with previous iOS 16.0 betas, ANE related threads are all on p-cores. However, artificial load still needed. Which means my original guess might be correct, i.e., there are both DVFS and scheduling issues. It seems the scheduling issue is kinda fixed, but the DVFS issue, which might be controlled by CLPC or other kernel extensions, is still there.

**Comment by freedomtan** [comment] 2022-09-27 05:36
Let's turn off the artificial load by default because "official" app doesn't have it.

**Comment by anhappdev** [comment] 2022-09-28 12:14
> Let's turn off the artificial load by default because "official" app doesn't have it.


Done. The build v2.0.0 (43) in TestFlight has it off by default.

**Comment by anhappdev** [comment] 2022-10-05 03:42
Let summarize what we have observed until now:
1. Setting a higher thread priority or dispatch queue priority have no impact on performance in this case
2. Using the new [ML Program](https://coremltools.readme.io/docs/ml-programs) model type can increase throughput in some devices, but decrease throughput in some other devices.
3. Using the `artificial load` can increase throughput in some devices, but decrease throughput in some other devices, and then behave differently on different OS versions.

So I am out of idea now what else to try. I think we can close this issue until something new happened.
The `artificial load` works well on some devices and is an optional setting, so should we merge it to the main branch?

**Comment by freedomtan** [comment] 2022-11-08 06:30
We can close this for now.

**Closed by freedomtan** 2022-11-08 06:30 UTC
Labels: priority:high, release:3.0, os:ios

**Comment by andyyeh75** [comment] 2023-09-02 14:35
Sorry Guru, 

I wonder the macbook and iphone results can be uploaded for review? So far only qualcomm results can be seen on the v3.0 page for Notebooks. [https://mlcommons.org/en/inference-mobile-30](https://mlcommons.org/en/inference-mobile-30/. ) Thanks a lot.

(only M1 data can be seen on this comment. https://github.com/mlcommons/mobile_app_open/issues/472#issuecomment-1230267686)
