### ISSUE TITLE
Update commonlibs to use libc++_shared.so from android-ndk r25c

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#747] opened 2023-07-04 13:03 UTC
Recently internal SNPE SDKs were updated to use android-ndk r25c. The libc++_shared.so that comes with the new ndk contains few more symbols which are required to build the qti backend with SNPE.
The libc++_shared.so currently being used in the app comes from r21e. 

I tried to upgrade the ndk version to r25c, but looks like Bazel doesn't yet support newer android NDK.

https://github.com/bazelbuild/bazel/issues/12889#issuecomment-917729095 (@freedomtan commented on one of the issues in bazel.)

However, i have tried that if we build with ndk-r21e itself but just ship the libc++_shared.so to the new version, then the app works fine for qualcomm backend.
Creating this issue to check if it's ok to do this? AFAIK, only Samsung backend needs to use the libc++_shared.so apart from qti backend. So, is it ok for us to update the libc++_shared.so? @AhmedTElthakeb, can you comment?

This update will be required for the next mlperf-v3.1 submission for qualcomm backend.

**Comment by mohitmundhragithub** [comment] 2023-07-04 13:06
https://github.com/mlcommons/mobile_app_open/blob/master/flutter/android/commonlibs/BUILD#L57

This is the library that needs to be updated.

**Comment by freedomtan** [comment] 2023-07-05 04:01
My impression is the newer Bazel does support newer NDK, but  TensorFlow didn't add related configurations. Things we can do 

- [ ] check if my impression is correct. If NO, we have to add some hacks. If YES, we can check how to use it.
- [ ] if YES, we may have other stuff to update,  as far as I can remember, we rely on settings of TensorFlow/TensorFlow Lite to build our C/C++ code. We may need to update some of them.

**Comment by freedomtan** [comment] 2023-07-05 07:47
confirmed that Bazel 6.x + [Android NDK Bazel Rules](https://github.com/bazelbuild/rules_android_ndk#android-ndk-bazel-rules) work fine with NDK 25.

1. `git clone https://github.com/bazelbuild/rules_android_ndk`
2. `cd  rules_android_ndk/examples/basic`
3. set `ANDROID_HOME` and `ANDROID_NDK_HOME`
4. `bazel build -c opt java/com/app:app --android_crosstool_top=@androidndk//:toolchain` works fine.

**Comment by mohitmundhragithub** [comment] 2023-07-05 11:05
> confirmed that Bazel 5.3.x/6.x (didn't check other versions) + [Android NDK Bazel Rules](https://github.com/bazelbuild/rules_android_ndk#android-ndk-bazel-rules) work fine with NDK 25.
> 
> 1. `git clone https://github.com/bazelbuild/rules_android_ndk`
> 2. `cd  rules_android_ndk/examples/basic`
> 3. set `ANDROID_HOME` and `ANDROID_NDK_HOME`
> 4. `bazel build -c opt java/com/app:app --android_crosstool_top=@androidndk//:toolchain` works fine.

i had tried with bazel 5.3.2 only, but saw some errors from protobuf and tensorflow.

**Comment by freedomtan** [comment] 2023-07-07 07:56
> > confirmed that Bazel 5.3.x/6.x (didn't check other versions) + [Android NDK Bazel Rules](https://github.com/bazelbuild/rules_android_ndk#android-ndk-bazel-rules) work fine with NDK 25.
> > 
> > 1. `git clone https://github.com/bazelbuild/rules_android_ndk`
> > 2. `cd  rules_android_ndk/examples/basic`
> > 3. set `ANDROID_HOME` and `ANDROID_NDK_HOME`
> > 4. `bazel build -c opt java/com/app:app --android_crosstool_top=@androidndk//:toolchain` works fine.
> 
> i had tried with bazel 5.3.2 only, but saw some errors from protobuf and tensorflow.

it is no surprise. As I said we use TensorFlow's NDK settings/rules, which were not updated to use the new [Android NDK Bazel Rules](https://github.com/bazelbuild/rules_android_ndk#android-ndk-bazel-rules)

**Comment by freedomtan** [comment] 2023-07-11 05:30
@AhmedTElthakeb to check if r25c libc++_shared.so with samsung backend.
@mohitmundhragithub to check if the r25c libc++_shared.so works with older SNPE versions.

possible hack: replace dependency lib path in you .so (SNPE) ELF. `hacking_editor "$...../libc++_shared.so" "/data/local/tmp/snpe_lib/'

**Comment by freedomtan** [comment] 2023-07-11 06:27
@mohitmundhragithub Yes, there is a small utility called [patchelf](https://github.com/NixOS/patchelf)

**Comment by mohitmundhragithub** [comment] 2023-07-17 10:00
> possible hack: replace dependency lib path in you .so (SNPE) ELF. `hacking_editor "$...../libc++_shared.so" "/data/local/tmp/snpe_lib/'

I was able to run old snpe + new libc++_shared.so.

**Comment by mohitmundhragithub** [comment] 2023-07-18 00:45
> @mohitmundhragithub Yes, there is a small utility called [patchelf](https://github.com/NixOS/patchelf)

I tried out this tool but it didn't help. Tried 2 commands:
1) patchelf --replace-needed libc++_shared.so libc++_shared_qti.so libSNPE.so
2) patchelf --set-soname libc++_shared_qti.so libc++_shared.so

But the app is unable to load libSNPE.so after trying out above. Error says unable to find symbols, which it was able to find before updating the elf.

**Comment by AhmedTElthakeb** [comment] 2023-07-25 04:20
We currently do not recommend mixing two ndks, and we suggest to find other alternative that does not involve mixing ndks.

**Comment by freedomtan** [comment] 2023-07-25 05:26
we need newer bazel to new bazel NDK rules
options to use newer NDK:
1. update TensorFlow's bazel building rules (because currently use TF's rules)
2. come up with our own rules (don't rely on NDK anymore)
@mohitmundhragithub suggested we may newer protobuf library and protoc

@freedomtan: not sure if we can finish this before submission date

**Comment by freedomtan** [comment] 2023-07-25 05:29
@AhmedTElthakeb may have more details to update next week.

**Comment by freedomtan** [comment] 2023-07-25 05:37
@RSMNYS please to to see if we can build code in flutter/cpp without using TensorFlow rules.

**Comment by freedomtan** [comment] 2023-08-01 05:22
For submission, this issue is not a road blocker. For integrated after submission, it could be.

**Comment by freedomtan** [comment] 2023-08-01 05:26
@freedomtan to check if patchelf works or not on Android devices.

**Comment by freedomtan** [comment] 2023-08-03 08:28
> > @mohitmundhragithub Yes, there is a small utility called [patchelf](https://github.com/NixOS/patchelf)
> 
> I tried out this tool but it didn't help. Tried 2 commands:
> 
> 1. patchelf --replace-needed libc++_shared.so libc++_shared_qti.so libSNPE.so
> 2. patchelf --set-soname libc++_shared_qti.so libc++_shared.so
> 
> But the app is unable to load libSNPE.so after trying out above. Error says unable to find symbols, which it was able to find before updating the elf.

@mohitmundhragithub had you replace other libc++_share.so in other SNPE libraries?

**Comment by mohitmundhragithub** [comment] 2023-08-03 08:38
> > > @mohitmundhragithub Yes, there is a small utility called [patchelf](https://github.com/NixOS/patchelf)
> > 
> > I tried out this tool but it didn't help. Tried 2 commands:
> > 
> > 1. patchelf --replace-needed libc++_shared.so libc++_shared_qti.so libSNPE.so
> > 2. patchelf --set-soname libc++_shared_qti.so libc++_shared.so
> > 
> > But the app is unable to load libSNPE.so after trying out above. Error says unable to find symbols, which it was able to find before updating the elf.
> 
> @mohitmundhragithub had you replaced libc++_share.so in other SNPE libraries? 

Yes. I did. But looks like libsnpe.so itself got unusable.

**Comment by freedomtan** [comment] 2023-08-03 10:00
> > > > @mohitmundhragithub Yes, there is a small utility called [patchelf](https://github.com/NixOS/patchelf)
> > > 
> > > 
> > > I tried out this tool but it didn't help. Tried 2 commands:
> > > 
> > > 1. patchelf --replace-needed libc++_shared.so libc++_shared_qti.so libSNPE.so
> > > 2. patchelf --set-soname libc++_shared_qti.so libc++_shared.so
> > > 
> > > But the app is unable to load libSNPE.so after trying out above. Error says unable to find symbols, which it was able to find before updating the elf.
> > 
> > 
> > @mohitmundhragithub had you replaced libc++_share.so in other SNPE libraries?
> 
> Yes. I did. But looks like libsnpe.so itself got unusable.

Hmm. I got it work on the 3.0 release app.
1.  download the app; unzip it
2. `patchelf --replace-needed libc++_shared.so libc++_foo.so libSNPE.so`
3. `patchelf --set-soname libfoo.so libc++_shared.so`, rename `libc++_shared.so` to `libfoo.so`.
4. push modified `libSNPE.so` and `libfoo.so` to /data/app/..../lib/arm64/

**Comment by mohitmundhragithub** [comment] 2023-08-03 11:22
I did exactly the same steps on the latest SNPE. But the error that i got was during loading libqtibackend.so which links to libSNPE.so and got some symbol errors when running the app.

just to clarify, after unzipping the app, you updated the libs. But, how did you run again? you made the apk again? it worked fine on device?

**Comment by freedomtan** [comment] 2023-08-03 12:56
> I did exactly the same steps on the latest SNPE. But the error that i got was during loading libqtibackend.so which links to libSNPE.so and got some symbol errors when running the app.
> 
> just to clarify, after unzipping the app, you updated the libs. But, how did you run again? you made the apk again? it worked fine on device?

FYR.

I didn't try newer SNPE. I just checked libs in the 3.0 release apk. I am told that, in newer SNPE, there are more libs depending on `libc++_shared.so`, that's why I asked if you changed them (rather than changing only the `libSNPE.so`)

I loaned a rooted 8 Gen 1 phone from a colleague. After hacking `libSNPE.so` and `libc++_shared.so`, I copied them to `/data/app/WHERE_THE_APP_IS/lib/arm64/` (remember this is a rooted phone), removed `libc++_shared.so`, closed the app, and relaunched it. That is, I installed the 3.0 release apk, then replaced the libSNPE.so, added libfoo.so, and remove libc++_shared.so. It worked for all benchmark items.

**Comment by mohitmundhragithub** [comment] 2023-08-17 14:01
Thanks a lot Freedom.
Turns out the version of patchelf i was using was creating the problem. On trying out 0.10 version, which installs directly from sudo apt-get, the same steps works fine.

This patch could be a short term thing, but i think we should find a long term solution for this issue.

**Comment by RSMNYS** [comment] 2023-08-28 13:14
Hi guys! Where I can find these libs: 

internal/libc++.so
internal/libeden_nn_on_system.so
internal/libenn_extension.so
internal/libenn_public_api_cpp.so
internal/libmbe1200_core.so
internal/libmbe2100_core.so
internal/libmbe2200_core.so
internal/libmbe2300_core.so
internal/libofi_rt_framework_user_vendor.so. 

Based on the documentation those should be here: https://github.com/mlcommons/mobile_back_samsung/tree/master/samsung_libs, but that repo is not found, or most probably I don't have an access to it. Can someone share the files with me, please?

**Comment by freedomtan** [comment] 2023-08-29 01:20
> Hi guys! Where I can find these libs:
> 
> internal/libc++.so internal/libeden_nn_on_system.so internal/libenn_extension.so internal/libenn_public_api_cpp.so internal/libmbe1200_core.so internal/libmbe2100_core.so internal/libmbe2200_core.so internal/libmbe2300_core.so internal/libofi_rt_framework_user_vendor.so.
> 
> Based on the documentation those should be here: https://github.com/mlcommons/mobile_back_samsung/tree/master/samsung_libs, but that repo is not found, or most probably I don't have an access to it. Can someone share the files with me, please?

as far as I can tell, most of them are from [Samsung ENN SDK](https://developer.samsung.com/neural/overview.html), which is not public available. It might take time to make that SDK available to you.

My suggestion: let's start from making building the default TFLite backend work with newer NDK possible.

**Comment by freedomtan** [comment] 2023-09-12 05:12
cpuinfo & XNNPACK <-- from TensorFlow, when try to build TFLite dependent stuff.

**Comment by freedomtan** [comment] 2023-09-15 12:42
FYI. In case you didn't notice it yet, thanks to @terryheo of Google, who contributed to early codebase of this app,   TensorFlow master branch started to support NDK r25 and later last week. 

I guess we can either
- update to recent TensorFlow master branch, or
- back up Terry's modifications to TF 2.8.

**Comment by freedomtan** [comment] 2023-09-18 09:18
I have some dirty hacks to make building the master branch with NDK r25c work. Didn't verify it, though. 
https://github.com/mlcommons/mobile_app_open/pull/new/ndk_25_quick_hack

**Comment by freedomtan** [comment] 2023-11-21 06:28
close this for now, since we merged the ndk r25c patch

**Closed by freedomtan** 2023-11-21 06:28 UTC
Labels: release:3.1
